apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp21
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp21
    app.kubernetes.io/part-of: testapp21
  name: testapp21
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: testapp21
status:
  loadBalancer: {}
